"""Windows local acceptance. Run from the repository root; never a CI test."""
import argparse
import csv
from datetime import datetime
import gzip
import json
import logging
import math
from pathlib import Path
import runpy
import subprocess
import sys
import tempfile
import threading
import time

from acceptance_support import SCENARIOS, SafeFormatter, Snapshot, confirmed_delay, correlate, expectations, final_results, sanitize, verdict, CAP_FIELDS, profile_bounds_valid, sustained_responses

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'src'))


class Quiet:
    @staticmethod
    def add_log(message):
        pass


def controller():
    from core.rtss_functions import RTSSController
    return RTSSController(Quiet())


def generated_configs(directory):
    """Defaults are generated by ConfigManager, never copied from user INIs."""
    from core.config_manager import ConfigManager

    class IsolatedConfig(ConfigManager):
        def load_or_init_configs(self):
            self.config_dir = str(directory)
            self.settings_path = str(directory / 'settings.ini')
            self.profiles_path = str(directory / 'profiles.ini')
            super().load_or_init_configs()
            self.settings_config['Preferences'].update({
                'first_launch_done': 'True', 'hide_loading_popup': 'True',
                'autopilot': 'False', 'launchonstartup': 'False',
                'minimizeonstartup': 'False', 'idle_mode': 'False'})
            self.settings_config['GlobalSettings']['profileonstartup_name'] = 'pythonw.exe'
            self.settings_config['GlobalSettings']['minvalidfps'] = '1'
            common = dict(self.profiles_config['Global'])
            common.update(capmethod='custom', monitoring_method='LibreHM',
                          delaybeforedecrease='3', delaybeforeincrease='3')
            for name, limits in [('Global', (30, 45, 60)), ('pythonw.exe', (24, 36, 48))]:
                values = dict(common, mincap=str(limits[0]), maxcap=str(limits[-1]),
                              customfpslimits=', '.join(map(str, limits)))
                self.profiles_config[name] = values
            for config, path in [(self.settings_config, self.settings_path),
                                 (self.profiles_config, self.profiles_path)]:
                with open(path, 'w', encoding='utf-8') as output:
                    config.write(output)
    return IsolatedConfig


def focus_game(pid):
    """Native focus, no input/click synthesis. Failure becomes missing RTSS evidence."""
    import ctypes
    from ctypes import wintypes
    user = ctypes.WinDLL('user32')
    user.SetForegroundWindow.argtypes = [wintypes.HWND]
    user.GetWindowThreadProcessId.argtypes = [wintypes.HWND, ctypes.POINTER(wintypes.DWORD)]
    callback_type = ctypes.WINFUNCTYPE(wintypes.BOOL, wintypes.HWND, wintypes.LPARAM)
    def visit(hwnd, _):
        owner = wintypes.DWORD()
        user.GetWindowThreadProcessId(hwnd, ctypes.byref(owner))
        if owner.value == pid and user.IsWindowVisible(hwnd):
            user.SetForegroundWindow(hwnd)
        return True
    user.EnumWindows(callback_type(visit), 0)


class Runtime:
    def __init__(self, directory, game_pid):
        self.directory = directory
        self.error_log_file = str(directory / 'limiter.log')
        self.config_factory = generated_configs(directory)
        self.game_pid = game_pid
        self.evidence = {}
        self.rows = []
        self.decisions = []
        self.revisions = {}
        self.live_rtss_samples = 0
        self.errors = []
        self.stage = 'restart_start'
        self.cycles = 0
        self.retired = []
        self.started = time.monotonic()
        self.due = 0
        self.switches = []
        self.clear_observations = []
        self.clear_write_indices = set()
        self.lock = threading.Lock()
        self.gui_thread = threading.get_ident()
        self.transitions = {}
        self.barriers = []
        self.pause = None
        self.samples = []
        self.overlaps = 0
        self.current_workers = (None, None)
        self.models = {}

    def configure_logging(self):
        handler = logging.FileHandler(self.error_log_file, encoding='utf-8')
        formatter = SafeFormatter('%(levelname)s %(message)s')
        handler.setFormatter(formatter)
        runtime = self
        class FailureCollector(logging.Filter):
            def filter(self, record):
                if len(runtime.errors) < 20:
                    runtime.errors.append('limiter error: ' + formatter.format(record))
                return True
        handler.addFilter(FailureCollector())
        logging.basicConfig(level=logging.ERROR, handlers=[handler], force=True)
        # The in-GUI log is also sanitized before retention.
        from core import logger
        original = logger.add_log
        logger.add_log = lambda message: original(sanitize(message))
        threading.excepthook = lambda args: self.errors.append('worker exception: ' + sanitize(args.exc_value))

    def initialized(self, app):
        self.app = app
        self.started = time.monotonic()
        original = app['cap_change_log'].record
        def record(row):
            safe = tuple(sanitize(value) for value in row)
            if safe[2] not in {'Global', 'pythonw.exe'}:
                raise RuntimeError('Uncontrolled profile attempted')
            if threading.get_ident() != self.gui_thread and threading.current_thread() is not self.current_workers[0]:
                self.errors.append('retired session attempted cap write')
            actual = app['rtss'].get_framerate_limit(safe[2], True)
            if actual is None or float(actual) != float(safe[4]):
                self.errors.append('RTSS cap readback mismatch')
            with self.lock:
                self.revisions[safe[0]] = app['profile_revision']
                self.rows.append(dict(zip(('time', 'session_number', 'profile', 'old_cap', 'new_cap',
                                           'reason', 'gpu_reading', 'cpu_reading', 'fps_mean'), safe)))
            original(safe)
        app['cap_change_log'].record = record
        queue_error = app['gui_queue']._on_error
        def error(fn, exc):
            self.errors.append('GUI queue exception: ' + sanitize(exc))
            queue_error(fn, exc)
        app['gui_queue']._on_error = error
        read_fps = app['rtss_manager'].get_fps_for_active_window
        def observed_fps():
            pause = self.pause
            if pause is not None and threading.current_thread() is pause[0]:
                pause[1].set()
                if not pause[2].wait(5):
                    self.errors.append("restart read barrier timeout")
            result = read_fps()
            if result[1] == 'pythonw.exe' and result[0] is not None and result[0] > 0:
                self.live_rtss_samples += 1
            return result
        app['rtss_manager'].get_fps_for_active_window = observed_fps
        # Controlled unavailability of PDH only. The underlying monitor still polls
        # real hardware; LibreHM and its physical values are untouched.
        real_gpu_monitor = app['gpu_monitor']
        class UnavailablePDH:
            @property
            def gpu_percentile(self):
                return None
            def __getattr__(self, name):
                return getattr(real_gpu_monitor, name)
        app['gpu_monitor'] = UnavailablePDH()
        self.switch(app, 'Global')
        focus_game(self.game_pid)

    def switch(self, app, profile):
        app['_load_profile_on_gui'](profile)
        ladder = sorted(float(x) for x in app['fps_utils'].current_stepped_limits())
        self.models[app['profile_revision']] = (profile, ladder)
        self.switches.append(ladder)

    def sensors(self, app, direction):
        """Real polled values with deliberately extreme temporary thresholds."""
        dpg = app['dpg']
        count = 0
        sensor = app['lhm_sensor']
        for info in app['cm'].sensor_infos:
            tag = 'input_' + info['parameter_id']
            if not dpg.does_item_exist(tag + '_enable'):
                continue
            dpg.set_value(tag + '_enable', False)
            key = (info['sensor_type'], info['sensor_name'])
            if info['hw_type'] != app['fps_utils'].HardwareType.Cpu:
                key = (info['sensor_type'], info.get('sensor_name_indexed') or info['sensor_name'])
                value = sensor.gpu_percentiles.get(key)
            else:
                value = sensor.cpu_percentiles.get(key)
            if value is None:
                continue
            count += 1
            dpg.set_value(tag + '_enable', True)
            dpg.set_value(tag + '_upper', '-100000' if direction == 'drop' else '100000')
            dpg.set_value(tag + '_lower', '-100001' if direction == 'drop' else '99999')
        return count > 0

    def callback(self, app):
        app['start_stop_callback'](None, None, app['cm'])

    def transition_observed(self, session, revision):
        self.transitions[(session, revision)] = time.time()

    def workers_started(self, monitor, plot):
        self.current_workers = (monitor, plot)

    def decision_observed(self, session, revision, result, gpu, captured_time):
        # Evaluate may cross a callback; never stamp its result with mutable globals.
        with self.app['session_lock']:
            if (session, revision) != (self.app['session_number'], self.app['profile_revision']) or not self.app['running']:
                return
            with self.lock:
                self.evidence['pdh_unavailable'] = bool(gpu) and all(v is None for v in gpu)
                self.decisions.append((captured_time, result, session, revision))

    def sample_observed(self, session, revision):
        if (session, revision) != (self.app['session_number'], self.app['profile_revision']):
            self.errors.append('retired worker appended history')
        self.samples.append((session, revision))

    def reset_observed(self, session, revision, history):
        # Called under the session lock immediately after actual state assignment.
        with self.lock:
            index = len(self.rows) - 1
            if index < 0 or index in self.clear_write_indices:
                return
            row = self.rows[index]
            if (row['reason'] not in ('decrease', 'increase')
                    or int(row['session_number']) != session
                    or self.revisions.get(row['time']) != revision):
                return
            self.clear_write_indices.add(index)
            self.clear_observations.append(
                not self.app['fps_values'] and not self.app['gpu_values']
                and not self.app['cpu_values'] and self.app['fps_mean'] == 0
                and history == (0, 0))

    def release_barriers(self):
        for _, _, release in self.barriers:
            release.set()

    def finish(self, app):
        self.release_barriers()
        self.evidence['switch_ladders'] = self.switches
        self.evidence['live_rtss_samples'] = self.live_rtss_samples
        # Release the non-reentrant session lock before exit_gui acquires it.
        with app.get('session_lock', self.lock):
            self.evidence['exit_running'] = app['running']
            self.evidence['exit_pre_cap'] = app['rtss'].get_framerate_limit('pythonw.exe', True)
            exit_session = app.get('session_number', -2) + 1
            controlled = (app.get('cm') is not None and app['cm'].current_profile == 'pythonw.exe'
                          and self.models.get(app.get('profile_revision')) == ('pythonw.exe', [24, 36, 48]))
        with self.lock:
            exit_start = len(self.rows)
        app['exit_gui']()
        with self.lock:
            exit_rows = list(self.rows[exit_start:])
        # Previously admitted writes may finish before exit invalidates the session.
        # Require them before both new-session restores, never after invalidation.
        pending = []
        while exit_rows and int(exit_rows[0]['session_number']) == exit_session - 1:
            pending.append(exit_rows.pop(0))
        chain_cap = self.evidence['exit_pre_cap']
        chain_valid = chain_cap is not None and 24 <= float(chain_cap) < 48
        for row in pending:
            old, new = row.get('old_cap'), float(row['new_cap'])
            chain_valid = (chain_valid and row['profile'] == 'pythonw.exe'
                           and old not in (None, '') and float(old) == float(chain_cap)
                           and new in (24, 36, 48)
                           and ((row['reason'] == 'decrease' and new < float(old))
                                or (row['reason'] == 'increase' and new > float(old))))
            chain_cap = new
        self.evidence['exit_restored'] = controlled and chain_valid and len(exit_rows) == 2 and [
            r['reason'] for r in exit_rows] == ['exit', 'exit_refresh'] and all(
            r['profile'] == 'pythonw.exe' and int(r['session_number']) == exit_session
            and float(r['new_cap']) == 48 for r in exit_rows
        ) and exit_rows[0].get('old_cap') not in (None, '') and float(
            exit_rows[0]['old_cap']) == float(chain_cap) and exit_rows[1].get('old_cap') not in (
                None, '') and float(exit_rows[1]['old_cap']) == 48
        self.evidence['exit_readback'] = float(app['rtss'].get_framerate_limit('pythonw.exe', True))
        self.evidence['cleared'] = (bool(self.clear_observations) and all(self.clear_observations)
                                    and self.clear_write_indices == {i for i, row in enumerate(self.rows)
                                        if row['reason'] in ('decrease', 'increase')})
        with self.lock:
            rows = list(self.rows)
            decisions = list(self.decisions)
        changes = [r for r in rows if r['reason'] in ('decrease', 'increase')]
        self.evidence['settled'] = len(changes) >= 2 and all(
            float(b['time'])-float(a['time']) >= 2 for a, b in zip(changes, changes[1:]))
        for reason, key, direction in [('decrease', 'drop_delay', (True, False)),
                                        ('increase', 'raise_delay', (False, True))]:
            matched = [r for r in changes if r['reason'] == reason]
            def delayed(row):
                timestamp = float(row['time'])
                revision = self.revisions[row['time']]
                candidates = [(d[0], d[1]) for d in decisions if d[2] == int(row['session_number']) and d[3] == revision]
                previous = max((float(r['time']) for r in rows if float(r['time']) < timestamp), default=0)
                previous = max(previous, self.transitions.get((int(row['session_number']), revision), timestamp))
                return confirmed_delay(timestamp, candidates, direction, previous)
            self.evidence[key] = bool(matched) and all(delayed(r) for r in matched)
        self.evidence['switch_response'] = bool(changes) and all(
            profile_bounds_valid(r, self.models.get(self.revisions.get(r['time']))) for r in rows) and any(
                r['profile'] == 'Global' and float(r['new_cap']) == 30 for r in changes) and any(
                r['profile'] == 'pythonw.exe' and float(r['new_cap']) == 24 for r in changes) and any(
                r['profile'] == 'pythonw.exe' and r['reason'] == 'increase' and float(r['new_cap']) == 48 for r in changes)
        self.save()

    def save(self):
        (self.directory / 'child.json').write_text(json.dumps({
            'evidence': self.evidence, 'errors': self.errors}), encoding='utf-8')

    def frame(self, app):
        assert threading.get_ident() == self.gui_thread
        now = time.monotonic()
        if now - self.started > 135:
            self.errors.append('scenario deadline exceeded')
            self.finish(app)
            return False
        if now < self.due:
            return
        if self.stage == 'restart_start':
            self.callback(app)
            self.stage = 'restart_arm'
        elif self.stage == 'restart_arm':
            old = self.current_workers[0]
            entered, release = threading.Event(), threading.Event()
            self.pause = (old, entered, release)
            self.barriers.append(self.pause)
            self.stage = 'restart_wait'
            self.barrier_deadline = now + 4
        elif self.stage == 'restart_wait':
            old, entered, release = self.pause
            if not entered.is_set():
                if now > self.barrier_deadline:
                    self.errors.append('old worker did not enter read barrier')
                    self.finish(app)
                    return False
                return
            self.retired.extend([old, self.current_workers[1]])
            self.callback(app)  # Stop invalidates the blocked pass.
            self.callback(app)  # Start replacement while old worker is still alive.
            self.overlaps += int(old.is_alive())
            self.cycles += 1
            self.pause = None
            release.set()
            self.stage = 'restart_arm' if self.cycles < 20 else 'quiet'
            if self.cycles == 20:
                self.current_sample_start = len(self.samples)
                self.due = now + 3
        elif self.stage == 'quiet':
            self.evidence['cycles'] = self.cycles
            self.evidence['restart_overlaps'] = self.overlaps
            self.evidence['retired_quiet'] = (app['running'] and self.overlaps == 20 and
                len(self.samples) > self.current_sample_start and
                all(not t.is_alive() for t in self.retired if t) and not self.errors)
            self.stage = 'warm'
            self.sensor_deadline = now + 20
            self.due = now + 6
        elif self.stage == 'warm':
            if not self.sensors(app, 'drop'):
                if now >= self.sensor_deadline:
                    self.errors.append('LibreHM physical sensor readiness timeout')
                    self.finish(app)
                    return False
                self.due = now + 1
                return
            self.evidence['physical_sensor'] = True
            self.stage = 'global_drop'
            self.due = now + 12
        elif self.stage == 'global_drop':
            self.switch(app, 'pythonw.exe')
            with app['session_lock']:
                app['_write_cap']('pythonw.exe', 48, 'controlled_baseline')
            self.sensors(app, 'drop')
            self.stage = 'profile_drop'
            self.due = now + 12
        elif self.stage == 'profile_drop':
            self.sensors(app, 'raise')
            self.stage = 'raise'
            self.due = now + 14
        elif self.stage == 'raise':
            self.sensors(app, 'drop')
            self.stage = 'exit'
            self.exit_deadline = now + 12
            self.due = now
        elif self.stage == 'exit':
            with app['session_lock']:
                cap = app['rtss'].get_framerate_limit('pythonw.exe', True)
                below_max = cap is not None and 24 <= float(cap) < 48
            if now >= self.exit_deadline:
                self.errors.append('final below-max pythonw cap timeout')
                self.finish(app)
                return False
            if below_max:
                self.finish(app)
                return False


def child(directory, pid):
    runtime = Runtime(directory, pid)
    try:
        runpy.run_path(str(ROOT / 'src/core/app.py'), init_globals={'_acceptance_runtime': runtime})
    except BaseException as exc:
        runtime.release_barriers()
        runtime.errors.append('limiter exception: ' + sanitize(exc))
        runtime.save()
        return 1
    finally:
        runtime.release_barriers()
    return 0


def wait_ready(process, path, timeout):
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if process.poll() is not None:
            raise RuntimeError('fake game exited before readiness')
        try:
            if json.loads(path.read_text())['ready']:
                return
        except (OSError, ValueError, KeyError):
            pass
        time.sleep(.1)
    raise TimeoutError('fake game readiness timeout')


def export_evidence(scratch, output, errors):
    rows, frames = [], []
    for path in scratch.glob('cap_changes_*.csv'):
        with path.open(newline='', encoding='utf-8') as source:
            for row in csv.DictReader(source):
                try:
                    if set(row) != set(CAP_FIELDS) or row['profile'] not in {'Global', 'pythonw.exe'}:
                        raise ValueError()
                    for key in ('time', 'session_number', 'old_cap', 'new_cap'):
                        if not math.isfinite(float(row[key])):
                            raise ValueError()
                    rows.append({k: sanitize(row[k]) for k in CAP_FIELDS})
                except (ValueError, TypeError):
                    errors.append('invalid controlled cap telemetry')
    rows.sort(key=lambda r: float(r['time']))
    path = scratch / 'frames.csv'
    try:
        with path.open(newline='') as source:
            reader = csv.reader(source)
            if next(reader, None) != ['timestamp', 'frame_time_ms']:
                errors.append('missing or invalid frame telemetry header')
            else:
                for row in reader:
                    try:
                        t, ms = map(float, row)
                        if not math.isfinite(t) or not math.isfinite(ms) or ms < 0:
                            raise ValueError()
                        frames.append((t, ms))
                    except (ValueError, TypeError):
                        errors.append('invalid numeric frame telemetry')
    except OSError:
        errors.append('frame telemetry unavailable')
    if not frames:
        errors.append('frame telemetry empty or unavailable')
    if not rows:
        errors.append('cap telemetry empty or unavailable')
    with (output / 'cap_changes.csv').open('w', newline='', encoding='utf-8') as dest:
        writer = csv.DictWriter(dest, fieldnames=CAP_FIELDS)
        writer.writeheader()
        writer.writerows(rows)
    target = output / ('frames.csv.gz' if path.exists() and path.stat().st_size > 3_000_000 else 'frames.csv')
    if target.suffix == '.gz':
        (output / 'frames.csv').unlink(missing_ok=True)
    with (gzip.open if target.suffix == '.gz' else open)(target, 'wt', newline='') as dest:
        writer = csv.writer(dest)
        writer.writerow(['timestamp', 'frame_time_ms'])
        writer.writerows(frames)
    return rows, frames


def run():
    if sys.platform != 'win32':
        raise SystemExit('Windows only; real interactive desktop and RTSS required')
    sha = subprocess.check_output(['git', 'rev-parse', '--short', 'HEAD'], cwd=ROOT, text=True).strip()
    output = ROOT / 'results' / (datetime.now().strftime('%Y%m%d_%H%M%S') + '_' + sha)
    output.mkdir(parents=True, exist_ok=False)
    report = {name: verdict(False, 'runtime not completed') for name in SCENARIOS}
    errors = []
    correlations = []
    observed = {}
    (output / 'cap_changes.csv').write_text('time,session_number,profile,old_cap,new_cap,reason,gpu_reading,cpu_reading,fps_mean\n', encoding='utf-8')
    (output / 'frames.csv').write_text('timestamp,frame_time_ms\n', encoding='utf-8')
    (output / 'limiter.log').write_text('', encoding='utf-8')
    game = limiter = None
    try:
        rtss = controller()
        profiles = Path(rtss.rtss_install_path) / 'Profiles'
        snapshot = Snapshot([profiles / 'Global', profiles / 'pythonw.exe.cfg'])
        flags = rtss.SetFlags(0xFFFFFFFF, 0)
        mask = rtss.RTSSHOOKSFLAG_LIMITER_DISABLED
    except BaseException as exc:
        detail = sanitize('RTSS preflight failed: ' + str(exc) + '; cap and frame telemetry unavailable')
        (output / 'summary.md').write_text('| Check | Result | Evidence |\n|---|---|---|\n' + ''.join(
            f'| {name} | FAIL | {detail} |\n' for name in SCENARIOS), encoding='utf-8')
        return 1
    with tempfile.TemporaryDirectory(prefix='dfl-acceptance-') as temp:
        scratch = Path(temp)
        try:
            # Fresh minimal profiles: never load/copy/enumerate existing private profiles.
            for name, cap in [('Global', 60), ('pythonw.exe.cfg', 0)]:
                (profiles / name).write_text('[Hooking]\nEnableHooking=1\nInjectionDelay=0\n'
                    'ApplicationDetectionLevel=3\n[Framerate]\nLimit=' + str(cap) + '\nLimitDenominator=1\n', encoding='utf-8')
            rtss.UpdateProfiles()
            rtss.enable_limiter()
            for name, cap in [('Global', 60), ('pythonw.exe', 0)]:
                if rtss.set_fractional_fps_direct(name, cap) is False:
                    raise RuntimeError('controlled cap initialization failed')
                observed.setdefault('controlled_initialization', []).append({'profile': name, 'cap': cap})
            pythonw = ROOT / '.venv/Scripts/pythonw.exe'
            if not pythonw.is_file():
                raise RuntimeError('Required .venv Scripts/pythonw.exe missing')
            game = subprocess.Popen([str(pythonw), str(ROOT / 'tests/fake_game.py'),
                '--ready-file', str(scratch / 'ready.json'), '--fps-file', str(scratch / 'fps.json'),
                '--frametime-file', str(scratch / 'frames.csv'), '--load', '2', '--duration', '150'],
                cwd=ROOT, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            wait_ready(game, scratch / 'ready.json', 20)
            # Give even the first limiter write a full pre-write telemetry window.
            time.sleep(3)
            limiter = subprocess.Popen([sys.executable, str(Path(__file__).resolve()), '--child',
                str(scratch), '--game-pid', str(game.pid)], cwd=ROOT,
                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            try:
                limiter.wait(timeout=145)
            except subprocess.TimeoutExpired:
                limiter.kill()
                limiter.wait(timeout=10)
                errors.append('limiter process timeout')
            try:
                game.wait(timeout=160)
            except subprocess.TimeoutExpired:
                game.kill()
                game.wait(timeout=10)
                errors.append('forced fake game termination: incomplete telemetry')
        except BaseException as exc:
            errors.append(sanitize(type(exc).__name__ + ': ' + str(exc)))
        finally:
            for process in (limiter, game):
                try:
                    if process and process.poll() is None:
                        if process is game:
                            try:
                                process.wait(timeout=160)
                                continue
                            except subprocess.TimeoutExpired:
                                errors.append('forced fake game termination: incomplete telemetry')
                        process.kill()
                        process.wait(timeout=10)
                except BaseException as exc:
                    errors.append('process cleanup failure: ' + sanitize(exc))
            try:
                snapshot.restore()
            except BaseException as exc:
                errors.append(sanitize(exc))
            finally:
                try:
                    rtss.SetFlags(~mask & 0xFFFFFFFF, flags & mask)
                    rtss.UpdateProfiles()
                except BaseException as exc:
                    errors.append('RTSS flags restoration failed: ' + sanitize(exc))
            try:
                if (scratch / 'limiter.log').exists():
                    lines = (scratch / 'limiter.log').read_text(encoding='utf-8').splitlines()
                    (output / 'limiter.log').write_text('\n'.join(sanitize(line) for line in lines
                        if any(word in line.lower() for word in ('error', 'exception', 'failed', 'traceback'))), encoding='utf-8')
            except BaseException as exc:
                errors.append('log evidence failure: ' + sanitize(exc))
        try:
            for label, process in [('limiter', limiter), ('fake game', game)]:
                if process is not None and process.returncode:
                    errors.append(f'{label} process exit code {process.returncode}')
            try:
                data = json.loads((scratch / 'child.json').read_text())
                observed.update(data['evidence'])
                errors.extend(data['errors'])
            except (OSError, ValueError, KeyError, TypeError):
                errors.append('child result missing or invalid')
            rows, frames = export_evidence(scratch, output, errors)
            correlations = correlate(rows, frames)
            if not correlations or not all(c['complete'] for c in correlations):
                errors.append('insufficient telemetry around cap writes')
            responses = sustained_responses(rows, frames)
            observed['frame_responses'] = sorted(responses)
            physical = {('Global', 30.0), ('pythonw.exe', 24.0), ('pythonw.exe', 48.0)} <= responses
            observed['switch_response'] = observed.get('switch_response') is True and physical
            observed['hooked'] = physical and observed.get('live_rtss_samples', 0) >= 6
            report = expectations(observed)
        except BaseException as exc:
            errors.append('evidence processing failed: ' + sanitize(exc))
    if errors:
        report = final_results({}, errors)
    text = '# Windows local acceptance\n\nCommit: ' + sha + '\n\n| Check | Result | Evidence |\n|---|---|---|\n'
    for name, result in report.items():
        text += f"| {name} | {result['status']} | {result['detail']} |\n"
    text += '\nObserved witnesses (generated acceptance state only):\n\n```json\n' + json.dumps(observed, sort_keys=True) + '\n```\n'
    text += '\nReal GUI, callbacks, decision loop, RTSS and fake game. Real LibreHM readings with controlled temporary thresholds; controlled PDH GPU unavailability; no injected LibreHM sensor feed.\n'
    text += '\nWorst frame-time spikes are informational in a fixed ±2 second window around every cap write; no spike pass threshold. Coverage requires at least three frames spanning write−1.5s through write+1.5s.\n\n| Write epoch | Worst ms | Coverage |\n|---|---|---|\n'
    for event in correlations:
        text += f"| {event['time']} | {event['worst_ms']} | {'PASS' if event['complete'] else 'FAIL'} |\n"
    (output / 'summary.md').write_text(sanitize(text), encoding='utf-8')
    print(str(output / 'summary.md'))
    return 0 if all(r['status'] == 'PASS' for r in report.values()) else 1


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--child', type=Path)
    parser.add_argument('--game-pid', type=int)
    args = parser.parse_args()
    sys.exit(child(args.child, args.game_pid) if args.child else run())
